### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by viral-1** [Innofactor/xrm-api#1]
The Authenticate method has been commented out and is not accessible. Do yo have an Authenticate method that uses a Promise?

**Comment by shytikov** [comment]
Hi!

I was actually thinking to remove that method at all, since normally you do not just authenticate, but rather supply that information to meaningful request, like `Retrieve` or `RetrieveMultiple`.

Can you tell me your usecase, if Authenticate is needed, I will add its promised version as well.

**Comment by viral-1** [comment]
Hi,
The README.md file shows the Authenticate method and the tests are failing because the method is missing.  I was hoping to use this library as it appears to be more up to date than the others on NPM... but sadly :-( I am unable to get it working.

**Comment by sagarpomal** [comment]
@viral-1 were you able to authenticate and connect to CRM? I am facing the same issue not able to Authenticate
@shytikov

**Comment by shytikov** [comment]
I've used library to authenticate against on-prem environments so far. Initial library was intended to work with Online only.

Currently I'm trying to implement IFD.

Normally I'm passing auth information to each method.

**Comment by sagarpomal** [comment]
@shytikov : i have online version, how do i authenticate initially to get auth info and pass it on to each method? What mechanism can i use to authenticate initially?

**Comment by laurihelkkula** [comment]
This repo has been inactive for many years and is not maintained anymore. We'll close all issues and archive this repository.
