### ISSUE TITLE
tried to run the constructor, call create, got this.

### ISSUE THREAD

**Issue by dmiddlecamp** [Innofactor/xrm-api#2]
```
Failure... ReferenceError: fetchEndpoints is not defined
    at authenticateUsingLiveId (.../server/node_modules/xrm-api/lib/auth.js:52:9)
    at Auth.Do (.../server/node_modules/xrm-api/lib/auth.js:244:13)
    at executePost (.../server/node_modules/xrm-api/lib/util.js:710:18)
    at .../server/node_modules/xrm-api/lib/util.js:726:13
    at Util.executePostPromised (.../server/node_modules/xrm-api/lib/util.js:725:16)
    at Message.Create (.../server/node_modules/xrm-api/lib/message.js:43:21)
    at Dynamics.Create (.../server/node_modules/xrm-api/index.js:24:24)
    at Object.<anonymous> (.../server/scripts/test-crm/main.js:37:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by dmiddlecamp** [comment]
looks like the default auth (unset) is authenticateUsingLiveId, which appears to be busted.

**Comment by dmiddlecamp** [comment]
looks like "microsoft_online" is also busted got this:

```
 ReferenceError: microsoftOnlineSaml is not defined
    at authenticateUsingMicrosoftOnline (.../server/node_modules/xrm-api/lib/auth.js:23:18)

```

**Comment by dmiddlecamp** [comment]
it looks like someone started refactoring the auth functions out of util into another class 'auth', but didn't update the references to these functions.  This couldn't have worked as is, why is this deployed to NPM?

**Comment by shytikov** [comment]
Hi,

I will check what's going on there and provide fix soon. If you have already proper solution to the issue, pull requests would be also welcome!

**Comment by simonschllng** [comment]
@dmiddlecamp do you have something better?

**Comment by shytikov** [comment]
@simonschllng it is possible to call methods providing authentication details directly there. The only problem that credentials is not cached. But this was problem in initial code too.

I'm working on implementing caching of this auth object. 

Will this approach work for you? Or you need something different to be implemented?

**Comment by simonschllng** [comment]
@shytikov I need a fix for the `ReferenceError: fetchEndpoints is not defined` issue. Caching is not that important...

**Comment by dmiddlecamp** [comment]
so after trying all the crm xml modules I could find, I discovered none of them work as expected.  So I used the Dynamics JSON Api directly:

basically a POST request to

```
https://YOUR_SITE.crm.dynamics.com/api/data/v8.1/tasks
```

I got the access token by creating a registered app under active directory for client_id and client_secret, then gave consent for that account via interactive oauth, then you can get a token by sending a post to:

https://login.microsoftonline.com/YOUR_TENANT/oauth2/token

with

```
client_id: "client_id",
client_secret: "client_secret",
grant_type: "password",
resource: "https://YOUR_SITE.crm.dynamics.com",
username: "username"
password: "password",
```

Quite a few hoops to jump through, but glad I got it working!

**Comment by simonschllng** [comment]
Thanks, @dmiddlecamp! I came to the same conclusion. Thanks for the hint with the JSON API. Where did you find the documentation?
I successfully authorized with OAuth and this package: https://github.com/Azure-Samples/active-directory-node-authentication

**Comment by laurihelkkula** [comment]
This repo has been inactive for many years and is not maintained anymore. We'll close all issues and archive this repository.
